### ISSUE TITLE
iOS integration

### ISSUE THREAD

**Issue by datomnurdin** [matiassingers/kl-parking-spots#3]
Is it possible to integrate with iOS app? Thanks.

**Comment by matiassingers** [comment]
That technically shouldn't be a problem, I'm just pulling and parsing some simple data.
The easiest solution for you might be do set up a quick API that just relays the data from this module.

**Comment by datomnurdin** [comment]
Thanks. I already deploy it on heroku :) https://kl-parking-spots.herokuapp.com/

**Comment by matiassingers** [comment]
That's awesome @datomnurdin - let me know if you use it in an iOS app ;)

**Comment by datomnurdin** [comment]
Actually I already done it last nite. You can check it here. I will credit your name there. https://github.com/datomnurdin/kl-parking-spots-swift
